const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulaity shirt in town',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'Adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high qulaity shirt in Canberra',
    },
    {
      _id: '3',
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 30,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulaity shirt in town',
    },
    {
      _id: '4',
      name: 'Adidas Fit Pants',
      slug: 'Adidas-Fit-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 80,
      countInStock: 10,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      description: 'high qulaity shirt in town',
    },
  ],
};
export default data;
